#!/bin/python3

import os,time


def testExpand():
	os.system("go run ./treecli -create-trie 1")
	print("[-->]  Created trie")
	time.sleep(5)
	os.system("go run ./treecli -insert -key 230 -value \"hahah\" -id 545 -token 37")
	print("[-->]  Inserted first value")
	time.sleep(5)
	os.system("go run ./treecli -insert -key 234 -value \"PaulskleinerPenis\" -id 545 -token 37")
	print("[-->] Inserted second value")
	time.sleep(5)
	os.system("go run ./treecli -insert -key 235 -value \"PaulskleinerPenis\" -id 545 -token 37")
	print("[-->] Inserted third value")
	print("[-->] Should now expand")
	time.sleep(5)
	os.system("go run ./treecli -find 235 -id 545 -token 37")
	print("[-->]  Found value")
	time.sleep(5)
	os.system("go run ./treecli -insert -key 236 -value \"PaulskleinerPenis\" -id 545 -token 37")
	print("[-->] Inserted 4th value")
	print("[-->] Should now expand")
	time.sleep(5)
	os.system("go run ./treecli -delete 235 -id 545 -token 37")
	print("[-->]  Found value")
	time.sleep(5)
	os.system("go run ./treecli -find 235 -id 545 -token 37")
	print("[-->]  Found value")
	time.sleep(5)
	os.system("go run ./treecli -traverse -id 545 -token 37")
	print("[-->] Travsere value")
	time.sleep(5)
	os.system("go run ./treecli -delete 234 -id 545 -token 37")
	print("[-->]  Delete Value")
	time.sleep(5)
	os.system("go run ./treecli -traverse -id 545 -token 37")
	print("[-->] Travsere value")
	time.sleep(5)
	os.system("go run ./treecli -delete 235 -id 545 -token 37")
	print("[-->]  Delete value")
	time.sleep(5)
	os.system("go run ./treecli -traverse -id 545 -token 37")
	print("[-->] Travsere value")
	time.sleep(5)
	os.system("go run ./treecli -delete 230 -id 545 -token 37")
	print("[-->] Delete value")
	time.sleep(5)
	os.system("go run ./treecli -traverse -id 545 -token 37")
	print("[-->] Travsere value")
	os.system("go run ./treecli -insert -key 233 -value \"PaulskleinerPenis\" -id 545 -token 37")
	print("[-->] Inserted new value")
	time.sleep(5)
	os.system("go run ./treecli -insert -key  229 -value \"hahah\" -id 545 -token 37")
	print("[-->]  Inserted new value")
	time.sleep(5)
	os.system("go run ./treecli -find 229 -id 545 -token 37")
	print("[-->]  Found value")
	time.sleep(5)
	os.system("go run ./treecli -find 233 -id 545 -token 37")
	print("[-->]  Found value")
	time.sleep(5)
	os.system("go run ./treecli -traverse -id 545 -token 37")
	print("[-->] Travsere value")
	time.sleep(2)


def main():
	print("Welcome to trietestingScript")
	print("Current Test will be Expand and Travserse after expanding")
	testExpand()
	print("Script finished")


if __name__ == "__main__":
	main()

